### ISSUE TITLE
发现了不得了的东西

### ISSUE THREAD

**Issue by GloomyGhost-MosquitoSeal** [NekoSilverFox/CPP#1]
https://github.com/NekoSilverFox/CPP/blob/5345064dffe092903a6878b39a448b0456121969/96.1%20-%20%E7%BA%AF%E8%99%9A%E6%9E%90%E6%9E%84%E7%9A%84%E7%BB%A7%E6%89%BF/96.1%20-%20%E7%BA%AF%E8%99%9A%E6%9E%90%E6%9E%84%E7%9A%84%E7%BB%A7%E6%89%BF.cpp#L18-L23

**Comment by NekoSilverFox** [comment]
被发现惹qwq

**Comment by GloomyGhost-MosquitoSeal** [comment]
嘤嘤嘤qwq
