### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by wuyuz** [NekoSilverFox/CPP#3]
您好，看见您的很多注释都是乱码，想问下您是采用的那种编码格式

**Comment by NekoSilverFox** [comment]
可以尝试使用 `GB2312`。感谢反应此问题，后续我会修复编码问题，统一更换为UFT-8。

**Comment by wuyuz** [comment]
嗯嗯，感谢您的回复，我再提问前已经试过GB2312了的，感觉还是不行，晚点我再试试吧，谢谢

**Comment by NekoSilverFox** [comment]
![image](https://user-images.githubusercontent.com/46406730/95849919-b337e500-0d58-11eb-96bb-d278a129852a.png)
或许可以使用 Sublime Text 进行打开
